[general]
import = ["/Users/niels/.config/alacritty/themes/one_dark.toml"]

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_title = false
# opacity = 0.95
option_as_alt = "OnlyLeft"

[window.padding]
x = 8
