# infat --config ~/.config/infat/config.toml

[extensions]
Brewfile = "Cursor"
Dockerfile = "Cursor"
html  = "Cursor"
ini   = "Cursor"
js    = "Cursor"
json  = "Cursor"
jsx   = "Cursor"
md    = "Cursor"
py    = "Cursor"
rs    = "Cursor"
sh    = "Cursor"
svg   = "Zen"
toml  = "Cursor"
ts    = "Cursor"
tsx   = "Cursor"
txt   = "Cursor"
yaml  = "Cursor"

[schemes]
mailto = "Superhuman"
web    = "Zen"

[types]
makefile   = "Cursor"
plain-text = "Cursor"
shell      = "Cursor"
sourcecode = "Cursor"
