# Inserts a blank line between shell prompts.
add_newline = true
# Double the time before Starship reports a timeout.
command_timeout = 1000

# [battery]
# disabled = true

# Replace the "❯" symbol in the prompt with "➜".
# [character]                            # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
# error_symbol = "[➜](bold red)"         # The "error_symbol" segment is being set to "➜" wbith the color "bold red"

[time]
disabled = false
format = "[$time]($style) "

[aws]
disabled = true

[buf]
disabled = true

[docker_context]
disabled = true
format = "via [$symbol]($style)" # Drop text. 

[gcloud]
disabled = true

[golang]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[hostname]
disabled = true
